/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as vulnerableVaultSol from './VulnerableVault.sol/index.js';
export { AttestationRegistry__factory } from './AttestationRegistry__factory.js';