/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPriceOracle__factory } from './IPriceOracle__factory.js';
export { VulnerableVault__factory } from './VulnerableVault__factory.js';