/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPriceOracle } from './IPriceOracle.js';
export type { VulnerableVault } from './VulnerableVault.js';