/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace AttestationRegistry {
      
    export type AttestationStruct = {target: AddressLike, risk: BigNumberish, score: BigNumberish, findingsHash: BytesLike, reportURI: string, auditor: AddressLike, timestamp: BigNumberish}

    export type AttestationStructOutput = [target: string, risk: bigint, score: bigint, findingsHash: string, reportURI: string, auditor: string, timestamp: bigint] & {target: string, risk: bigint, score: bigint, findingsHash: string, reportURI: string, auditor: string, timestamp: bigint }
  
    }

  export interface AttestationRegistryInterface extends Interface {
    getFunction(nameOrSignature: "attest" | "attestations" | "attestationsOf" | "latestOf" | "total"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Attested"): EventFragment;

    encodeFunctionData(functionFragment: 'attest', values: [AddressLike, BigNumberish, BigNumberish, BytesLike, string]): string;
encodeFunctionData(functionFragment: 'attestations', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'attestationsOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'latestOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'total', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'attest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'attestations', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'attestationsOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'latestOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'total', data: BytesLike): Result;
  }

  
    export namespace AttestedEvent {
      export type InputTuple = [id: BigNumberish, target: AddressLike, risk: BigNumberish, score: BigNumberish, findingsHash: BytesLike, auditor: AddressLike];
      export type OutputTuple = [id: bigint, target: string, risk: bigint, score: bigint, findingsHash: string, auditor: string];
      export interface OutputObject {id: bigint, target: string, risk: bigint, score: bigint, findingsHash: string, auditor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AttestationRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): AttestationRegistry;
    waitForDeployment(): Promise<this>;

    interface: AttestationRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    attest: TypedContractMethod<
      [target: AddressLike, risk: BigNumberish, score: BigNumberish, findingsHash: BytesLike, reportURI: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    attestations: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, string, string, string, bigint] & {target: string, risk: bigint, score: bigint, findingsHash: string, reportURI: string, auditor: string, timestamp: bigint }],
      'view'
    >
    

    
    attestationsOf: TypedContractMethod<
      [target: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    latestOf: TypedContractMethod<
      [target: AddressLike, ],
      [AttestationRegistry.AttestationStructOutput],
      'view'
    >
    

    
    total: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'attest'): TypedContractMethod<
      [target: AddressLike, risk: BigNumberish, score: BigNumberish, findingsHash: BytesLike, reportURI: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'attestations'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, string, string, string, bigint] & {target: string, risk: bigint, score: bigint, findingsHash: string, reportURI: string, auditor: string, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'attestationsOf'): TypedContractMethod<
      [target: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'latestOf'): TypedContractMethod<
      [target: AddressLike, ],
      [AttestationRegistry.AttestationStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'total'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'Attested'): TypedContractEvent<AttestedEvent.InputTuple, AttestedEvent.OutputTuple, AttestedEvent.OutputObject>;

    filters: {
      
      'Attested(uint256,address,uint8,uint8,bytes32,address)': TypedContractEvent<AttestedEvent.InputTuple, AttestedEvent.OutputTuple, AttestedEvent.OutputObject>;
      Attested: TypedContractEvent<AttestedEvent.InputTuple, AttestedEvent.OutputTuple, AttestedEvent.OutputObject>;
    
    };
  }