/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as vulnerableVaultSol from './VulnerableVault.sol/index.js';
export type { vulnerableVaultSol };
export type { AttestationRegistry } from './AttestationRegistry.js';
export * as factories from './factories/index.js';
export { AttestationRegistry__factory } from './factories/AttestationRegistry__factory.js';
export type { IPriceOracle } from './VulnerableVault.sol/IPriceOracle.js';
export { IPriceOracle__factory } from './factories/VulnerableVault.sol/IPriceOracle__factory.js';
export type { VulnerableVault } from './VulnerableVault.sol/VulnerableVault.js';
export { VulnerableVault__factory } from './factories/VulnerableVault.sol/VulnerableVault__factory.js';